[package]
name = "pwgen"
version = "1.1.0"
authors = ["Box <box@sysn.co.uk"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "4.5.7"
clipboard = "0.5.0"
