[package]
name = "pwgrs"
version = "1.1.1"
authors = ["Box <box@sysn.co.uk>"]
edition = "2021"

[[bin]]
name = "pwgrs"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "4.5.7"
clipboard = "0.5.0"
